version: '3.1'

volumes:
  data:

services:
  spaceflight-booking:
    build: .
    environment:
      - COMPOSE_PROJECT_NAME
#    ports:
#      - "7001:8080"
    command: echo "${COMPOSE_PROJECT_NAME} started"

#  mariadb:
#    image: "mariadb:latest"
#    container_name: "mariadb-spaceflight-booking"
#    restart: always
#    env_file:
#    - maria.env
#    environment:
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#    volumes:
#      - data:/var/lib/mysql
#    ports:
#      - "3306:3306"
