version: '3.1'

services:
  spaceflight-booking:
    build: .
    environment:
      - COMPOSE_PROJECT_NAME
    ports:
      - "7001:8080"
    command: echo "${COMPOSE_PROJECT_NAME} started"

  mariadb:
    image: "mariadb:latest"
    container_name: "mariadb-spaceflight-booking"
    ports:
      - "9080:8080"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
