spring:
  datasource:
    #url: jdbc:mariadb://localhost:3306/spaceflight-booking
    url: jdbc:h2:mem:spaceflight-booking
    username: user
    password: password
    #driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: org.h2.Driver
  jpa:
    #database-platform: org.hibernate.dialect.MariaDB106Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true